---
# oraclejdk
#
# Dependencies:
#
#   * common
#
# Example play:
#
#   roles:
#   - common
#   - oraclejdk

<<<<<<< HEAD
- name: install debian needed pkgs
  apt: pkg={{ item }}
  with_items: oraclejdk_debian_pkgs
  tags:
    - install
    - install:system-requirements

- name: download Oracle Java
  shell: >
    curl -b gpw_e24=http%3A%2F%2Fwww.oracle.com -b oraclelicense=accept-securebackup-cookie -O -L {{ oraclejdk_url }}
    executable=/bin/bash
    chdir=/var/tmp
    creates=/var/tmp/{{ oraclejdk_file }}
  tags:
    - install
    - install:system-requirements

- name: create jvm dir
  file: >
    path=/usr/lib/jvm
    state=directory
    owner=root
    group=root
  tags:
    - install
    - install:configuration

- name: untar Oracle Java
  shell: >
    tar -C /usr/lib/jvm -zxvf /var/tmp/{{ oraclejdk_file }}
    executable=/bin/bash
    creates=/usr/lib/jvm/{{ oraclejdk_base }}
  tags:
    - install
    - install:configuration

- name: create symlink expected by elasticsearch
  file: src=/usr/lib/jvm/{{ oraclejdk_base }} dest={{ oraclejdk_link }} state=link force=yes
  tags:
    - install
    - install:configuration

- name: update alternatives java
  alternatives: >
    name={{ item }}
    link="/usr/bin/{{ item }}"
    path="/usr/lib/jvm/{{ oraclejdk_base }}/bin/{{ item }}"
=======
- name: Install debian needed pkgs
  apt:
    name: "{{ item }}"
  with_items: "{{ oraclejdk_debian_pkgs }}"

- name: Download Oracle Java
  shell: "curl -b gpw_e24=http%3A%2F%2Fwww.oracle.com -b oraclelicense=accept-securebackup-cookie -O -L {{ oraclejdk_url }}"
  args:
    executable: /bin/bash
    chdir: /var/tmp
    creates: "/var/tmp/{{ oraclejdk_file }}"

- name: Create jvm dir
  file:
    path: /usr/lib/jvm
    state: directory
    owner: root
    group: root

- name: Untar Oracle Java
  shell: "tar -C /usr/lib/jvm -zxvf /var/tmp/{{ oraclejdk_file }}"
  args:
    executable: /bin/bash
    creates: "/usr/lib/jvm/{{ oraclejdk_base }}"

- name: Create symlink expected by elasticsearch
  file:
    src: "/usr/lib/jvm/{{ oraclejdk_base }}"
    dest: "{{ oraclejdk_link }}"
    state: link
    force: yes

- name: Update alternatives java
  alternatives:
    name: "{{ item }}"
    link: "/usr/bin/{{ item }}"
    path: "/usr/lib/jvm/{{ oraclejdk_base }}/bin/{{ item }}"
>>>>>>> upstream/master
  with_items:
    - java
    - javac
    - javaws
<<<<<<< HEAD
  tags:
    - install
    - install:configuration

- name: add JAVA_HOME for Oracle Java
  template: src=java.sh.j2 dest=/etc/profile.d/java.sh owner=root group=root mode=0755
  tags:
    - install
    - install:configuration
=======
    - jarsigner

- name: Add JAVA_HOME for Oracle Java
  template:
    src: "java.sh.j2"
    dest: "/etc/profile.d/java.sh"
    owner: root
    group: root
    mode: "0755"
>>>>>>> upstream/master
