- name: Deploy edxapp
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - common_vars
    - edxapp
    - {role: demo, when: "edx_install_demo is defined and edx_install_demo == true"}
