version: '2'
#
# Single Docker Compose cluster that will eventually start
# all edX services in a single flock of coordinated containers
#
# This work is currently experimental and a number of services
# are missing entirely.  Containers that are present will not
# currently work without manual steps.  We are working on
# addressing that.
#
# When running compose you must pass in two environment variables
#
# DOCKER_EDX_ROOT which points to the directory into which you checkout
# your edX source code.  For example, assuming the following directory
# structure under /home/me
#
# |-- edx-src
# |   |-- discovery
# |   |-- cs_comments_service
# |   |-- edx_discovery
# |   |-- edx-platform
# |   |-- xqueue

# you would define DOCKER_EDX_ROOT="/home/me/edx-src"
#
# DOCKER_DATA_ROOT is the location on your host machine where Docker
# guests can access your local filesystem for storing persistent data
# files, say MongoDB or MySQL data files.
#
services:
 db:
  image: mysql:5.7
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_DATABASE: edxapp
   MYSQL_USER: edxapp001
   MYSQL_PASSWORD: password
  volumes:
   - ${DOCKER_DATA_ROOT}/mysql/data:/var/lib/mysql
  ports:
   - 3306:3306


 mongo:
  image: mongo:3.3
  volumes:
   - ${DOCKER_DATA_ROOT}/mongo/data:/data/db
  ports:
   - 27017:27017
  command: --auth


# Need to build our own for ES 0.9
 es:
  image: opensaas/edx-elasticsearch
  volumes:
   - ${DOCKER_DATA_ROOT}/elasticsearch/data:/data
  ports:
   - 9100:9100
   - 9200:9200
   - 9300:9300


 memcache:
  image: memcached:1.4.24
  volumes:
   - ${DOCKER_DATA_ROOT}/memcache/data:/data
  ports:
   - 11211:11211


 nginx:
  image: opensaas/edx-nginx
  ports:
   - 80:80
   - 443:443


 rabbitmq:
  image: rabbitmq:3.5.3
  volumes:
   - ${DOCKER_DATA_ROOT}/rabbitmq/data:/var/lib/rabbitmq
  ports:
   - 5672:5672

 forums:
  container_name: forums
  # Image built from the opencraft fork as it fixes
  # an auth bug.  Update when the change merges
  # upstream
  image: edxops/forums:opencraft-v2
  volumes:
   - ${DOCKER_EDX_ROOT}/cs_comments_service:/edx/app/forum/cs_comments_service
  ports:
   - 4567:4567
   
 xqueue:
  image: opensaas/edx-xqueue
  ports:
   - 8040:8040
   - 18040:18040
  volumes:
   - ${DOCKER_EDX_ROOT}/xqueue:/edx/app/edxapp/xqueue


 lms:
  image: opensaas/edxapp
  ports:
   - 8000:8000
   - 18000:18000
  volumes:
   - ${DOCKER_EDX_ROOT}/edx-platform:/edx/app/edxapp/edx-platform


 cms:
  image: opensaas/edxapp
  ports:
   - 8010:8010
   - 18010:18010
  volumes:
   - ${DOCKER_EDX_ROOT}/edx-platform:/edx/app/edxapp/edx-platform
