---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role edx_service
#
# Overview:
#
# This role performs the repetive tasks that most edX roles
# require in our default configuration.
#
# Example play:
#
# Rather than being included in the play, this role
# is included as a dependency by other roles in the meta/main.yml
# file.  The including role should add the following
# depency definition.
#
# dependencies:
#   - role: edx_service
#     edx_service_name: "hotg"
#     edx_service_config: "{{ structure_to_be_written_to_config_file_in_/edx/etc }}"
#     edx_service_repos:
#       - PROTOCOL: [https/ssh]
#         DOMAIN: github.com
#         PATH: edx
#         REPO: hotg
#         VERSION: master
#         DESTINATION: "/edx/app/hotg/hotg"
#         SSH_KEY: <required if PROTOCOL==ssh>
#       - PROTOCOL
#         ...
#     edx_service_user: hotg_system_user
#     edx_service_home: "/edx/app/hotg"
#     edx_service_packages:
#       debian: [ pkg1, pkg2, pkg3 ]      
#       redhat: [ pkg4, pkg5 ]
#

- name: write out app config file
  template: >
    src=config.yml.j2
    dest={{ COMMON_CFG_DIR  }}/{{ edx_service_name }}.yml
    mode=0644
  when: edx_service_config is defined
  tags:
    - install
    - install:configuration
  
- name: install a bunch of system packages on which edx_service relies
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  with_items: edx_service_packages.debian
  when: ansible_distribution in common_debian_variants
  tags:
    - install
    - install:system-requirements

- name: install a bunch of system packages on which edx_service relies
  yum: pkg={{ item }} state=present
  with_items: edx_service_name.redhat
  when: ansible_distribution in common_redhat_variants
  tags:
    - install
    - install:system-requirements

- name: get instance information
  action: ec2_facts
  tags:
    - to-remove
  #old syntax - should be fixed

- name: tag instance
  ec2_tag_local: resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }}
  args:
    tags:
      - Name: version:{{edx_service_name}}
        Value: "{{ item.0.DOMAIN }}/{{ item.0.PATH }}/{{ item.0.REPO }} {{ item.1.after |truncate(7,True,'') }}"
  when: item.1.after is defined and COMMON_TAG_EC2_INSTANCE and edx_service_repos is defined
  with_together: 
    - edx_service_repos
    - code_checkout.results
  tags:
    - to-remove

#TODO: restart supervisor- depends on supervisor being refactored into this role
